# Localization Module
# Provides multi-language support for the application

# Global variable to store current language
$script:CurrentLanguage = "en"

# Translation dictionary
$script:Translations = @{
    "en" = @{
        # Menu
        "menu_title" = "Runner Manager"
        "menu_subtitle" = "Advanced Infrastructure Suite"
        "menu_platform" = "Platform"
        "menu_instance" = "Instance"
        "menu_repository" = "Repository"
        "menu_group" = "Group"
        "menu_project" = "Project"
        "menu_target" = "Target"
        "menu_not_configured" = "Not configured"
        "menu_token" = "Token"
        "menu_configured" = "Configured"
        "menu_not_set" = "Not set"
        "menu_telegram" = "Telegram"
        "menu_enabled" = "Enabled"
        "menu_disabled" = "Disabled"
        "menu_users" = "users"
        "menu_docker_runners" = "Docker Runners"
        "menu_containers" = "containers"
        "menu_local_runners" = "Local Runners"
        "menu_active_runner" = "Active Runner"
        "menu_path" = "Path"
        
        # Common
        "invalid_option" = "Invalid option. Please try again."
        "press_enter" = "Press Enter to continue"
        "goodbye" = "Thank you for using Octopus Runner Manager!"
        "cancelled" = "Cancelled"
        "error" = "Error"
        "success" = "Success"
        "warning" = "Warning"
        "yes" = "yes"
        "no" = "no"
        
        # Platform
        "platform_github" = "GitHub Actions"
        "platform_gitlab" = "GitLab CI/CD"
        "platform_selection_title" = "Platform Selection"
        "platform_select_prompt" = "Select platform:"
        "platform_invalid" = "Invalid selection"
        
        # Target Type
        "target_type_title" = "Target Type Selection"
        "target_type_prompt" = "Select target type:"
        "target_type_project" = "Project (single repository)"
        "target_type_group" = "Group (multiple projects)"
        
        # Token Configuration
        "token_config_title" = "{0} Token Configuration"
        "token_config_help_github" = "Required permissions:"
        "token_config_perm_repo" = "repo (Full control of private repositories)"
        "token_config_perm_workflow" = "workflow (Update GitHub Action workflows)"
        "token_config_perm_api" = "api (Full API access)"
        "token_config_create_github" = "Create token at: https://github.com/settings/tokens"
        "token_config_create_gitlab" = "Create token at: {0}/-/profile/personal_access_tokens"
        "token_config_create_gitlab_self" = "For self-hosted: https://your-gitlab.com/-/profile/personal_access_tokens"
        "token_current" = "Current token"
        "token_update" = "Update token? (y/n)"
        "token_enter" = "Enter your {0} token"
        "token_saved" = "Token saved successfully"
        
        # Token Storage
        "token_storage_question" = "How would you like to store the token?"
        "token_storage_env" = "Environment Variable (persistent, survives restarts)"
        "token_storage_file" = "Encrypted File (stored in config file)"
        "token_storage_session" = "Session Only (temporary, lost on exit)"
        
        # Repository Selection
        "repo_selection_title" = "{0} Selection"
        "repo_token_not_configured" = "{0} token not configured"
        "repo_configure_token_first" = "Please configure your token first (Option 1)"
        "repo_fetching" = "Fetching {0}..."
        "repo_projects" = "projects"
        "repo_groups" = "groups"
        "repo_repositories" = "repositories"
        "repo_none_found" = "No {0} found"
        "repo_search_prompt" = "Search {0} (enter part of name):"
        "repo_search" = "Search"
        "repo_no_match" = "No {0} matching '{1}'"
        "repo_found" = "Found {0} {1}"
        "repo_select_prompt" = "Select {0} (1-{1})"
        "repo_set_to" = "{0} set to: {1}"
        "repo_error_fetching" = "Error fetching {0}: {1}"
        "repo_page_info" = "Page {0} of {1} (Total: {2} repositories)"
        "repo_visibility_private" = "[Private]"
        "repo_visibility_public" = "[Public]"
        "repo_commands" = "Commands:"
        "repo_cmd_select" = "[number] - Select repository"
        "repo_cmd_next" = "n - Next page"
        "repo_cmd_prev" = "p - Previous page"
        "repo_cmd_search" = "s - Search/Filter"
        "repo_cmd_clear" = "c - Clear filter"
        "repo_cmd_quit" = "q - Quit"
        "repo_enter_command" = "Enter command or number"
        "repo_search_filter" = "Search filter: '{0}'"
        "repo_invalid_selection" = "Invalid selection"
        "repo_last_page" = "Already on last page"
        "repo_first_page" = "Already on first page"
        "repo_enter_search" = "Enter search term (searches in name and description)"
        "repo_no_match_found" = "No repositories match '{0}'"
        "repo_filter_cleared" = "Filter cleared"
        "repo_invalid_command" = "Invalid command"
        "repo_fetching_repos" = "Fetching your repositories..."
        
        # Runner Status
        "status_title" = "Runner Status"
        "status_repository" = "Repository"
        "status_token" = "Token"
        "status_installation" = "Installation"
        "status_installed_at" = "Installed at {0}"
        "status_not_installed" = "Not installed"
        "status_autostart" = "Auto-Start"
        "status_process" = "Process"
        "status_running_pid" = "Running (PID: {0})"
        "status_not_running" = "Not running"
        "status_running" = "running"
        
        # Multi-Runner
        "multirunner_title" = "Multi-Runner Management"
        "multirunner_local_runners" = "Local Runners"
        "multirunner_no_runners" = "No local runners configured"
        "multirunner_tip" = "Tip: Use option 1 to add a new runner"
        "multirunner_add" = "Add new runner"
        "multirunner_select" = "Select active runner"
        "multirunner_remove" = "Remove runner"
        "multirunner_back" = "Back to main menu"
        "multirunner_add_title" = "Add New Local Runner"
        "multirunner_enter_name" = "Enter runner name (e.g., 'Main Runner', 'Backup Runner'):"
        "multirunner_name" = "Name"
        "multirunner_name_empty" = "Runner name cannot be empty"
        "multirunner_enter_path" = "Enter runner installation path:"
        "multirunner_example" = "Example"
        "multirunner_path" = "Path"
        "multirunner_using_default" = "Using default path: {0}"
        "multirunner_path_exists" = "Warning: Path already exists. Runner may already be installed."
        "multirunner_continue" = "Continue anyway? (y/n)"
        "multirunner_current_repo" = "Current repository: {0}"
        "multirunner_use_current" = "Use current repository? (y/n)"
        "multirunner_enter_repo" = "Enter repository (owner/repo):"
        "multirunner_repo_empty" = "Repository cannot be empty"
        "multirunner_added" = "Runner added successfully!"
        "multirunner_runner_id" = "Runner ID: {0}"
        "multirunner_next_steps" = "Next steps:"
        "multirunner_step_select" = "Select this runner as active (option 2)"
        "multirunner_step_install" = "Install the runner (option 5 in main menu)"
        "multirunner_select_title" = "Select Active Runner"
        "multirunner_no_runners_add" = "No runners configured. Add a runner first."
        "multirunner_cancel" = "Cancel"
        "multirunner_invalid_selection" = "Invalid selection"
        "multirunner_active_set" = "Active runner set to: {0}"
        "multirunner_remove_title" = "Remove Local Runner"
        "multirunner_remove_warning" = "Warning: This will remove runner configuration"
        "multirunner_remove_files_kept" = "Runner files in {0} will NOT be deleted"
        "multirunner_confirm" = "Are you sure? (yes/no)"
        "multirunner_removed" = "Runner removed from configuration"
        
        # Docker
        "docker_title" = "Docker Container Management"
        "docker_not_installed" = "Docker is not installed or not in PATH"
        "docker_install_prompt" = "Please install Docker Desktop from: https://www.docker.com/products/docker-desktop"
        "docker_not_running" = "Docker daemon is not running"
        "docker_start_prompt" = "Please start Docker Desktop and try again"
        "docker_checking" = "Checking Docker status..."
        "docker_available" = "Docker is available"
        
        # Telegram
        "telegram_config_title" = "Telegram Notification Configuration"
        "telegram_current_status" = "Current status:"
        "telegram_status_enabled" = "ENABLED"
        "telegram_status_disabled" = "DISABLED"
        "telegram_registered_users" = "Registered users: {0}"
        "telegram_option_enable" = "Enable/Configure Telegram notifications"
        "telegram_option_add_user" = "Add user (Chat ID)"
        "telegram_option_remove_user" = "Remove user"
        "telegram_option_test" = "Test notification"
        "telegram_option_disable" = "Disable notifications"
        "telegram_option_back" = "Back"
        "telegram_enter_token" = "Enter Telegram Bot Token"
        "telegram_bot_connected" = "Bot connected: @{0}"
        "telegram_failed_connect" = "Failed to connect to Telegram bot: {0}"
        "telegram_getting_chat_ids" = "Getting available chat IDs..."
        "telegram_found_chat_ids" = "Found chat IDs: {0}"
        "telegram_add_all_chats" = "Add all found chat IDs? (y/n)"
        "telegram_enabled" = "Telegram notifications enabled!"
        "telegram_configure_first" = "Please configure Telegram bot first (option 1)"
        "telegram_enter_chat_id" = "Enter Chat ID to add"
        "telegram_user_added" = "User added successfully!"
        "telegram_user_exists" = "This user is already registered"
        "telegram_no_users" = "No users registered"
        "telegram_registered_users_list" = "Registered users:"
        "telegram_enter_number_remove" = "Enter number to remove"
        "telegram_user_removed" = "User removed successfully!"
        "telegram_not_configured" = "Telegram notifications are not configured"
        "telegram_sending_test" = "Sending test notification..."
        "telegram_test_success" = "Successfully sent to {0} of {1} chats"
        "telegram_test_failed" = "Failed to send to all chats"
        "telegram_failed_chats" = "Failed chats:"
        "telegram_chat_id" = "Chat ID: {0}"
        "telegram_common_issues" = "Common issues:"
        "telegram_issue_not_started" = "User hasn't started conversation with bot"
        "telegram_solution_start" = "Solution: Open Telegram, search for your bot, click START"
        "telegram_issue_blocked" = "User blocked the bot"
        "telegram_solution_unblock" = "Solution: Unblock bot in Telegram settings"
        "telegram_issue_invalid_id" = "Invalid Chat ID"
        "telegram_solution_get_id" = "Solution: Get correct Chat ID from @userinfobot"
        "telegram_disabled" = "Telegram notifications disabled"
        "telegram_how_to_get_id" = "How to get your Telegram Chat ID"
        "telegram_method_userinfobot" = "Method 1: Using @userinfobot"
        "telegram_step_search" = "Open Telegram and search for @userinfobot"
        "telegram_step_start" = "Start conversation and send /start"
        "telegram_step_reply" = "Bot will reply with your Chat ID"
        "telegram_method_auto" = "Method 2: Automatic detection"
        "telegram_step_send_message" = "Send any message to your bot"
        "telegram_step_detect" = "This tool will detect your Chat ID"
        "telegram_checking_messages" = "Checking for messages..."
        "telegram_found_chats" = "Found {0} chat(s):"
        "telegram_username" = "Username: @{0}"
        "telegram_name" = "Name: {0}"
        "telegram_type" = "Type: {0}"
        "telegram_no_messages" = "No messages found."
        "telegram_send_message_prompt" = "Please send a message to your bot and try again."
        "telegram_error_getting_ids" = "Failed to get chat IDs: {0}"
    }
    
    "ru" = @{
        # Меню
        "menu_title" = "Менеджер Runner'ов"
        "menu_subtitle" = "Продвинутый набор инфраструктуры"
        "menu_platform" = "Платформа"
        "menu_instance" = "Инстанс"
        "menu_repository" = "Репозиторий"
        "menu_group" = "Группа"
        "menu_project" = "Проект"
        "menu_target" = "Цель"
        "menu_not_configured" = "Не настроено"
        "menu_token" = "Токен"
        "menu_configured" = "Настроен"
        "menu_not_set" = "Не установлен"
        "menu_telegram" = "Telegram"
        "menu_enabled" = "Включен"
        "menu_disabled" = "Отключен"
        "menu_users" = "пользователей"
        "menu_docker_runners" = "Docker Runner'ы"
        "menu_containers" = "контейнеров"
        "menu_local_runners" = "Локальные Runner'ы"
        "menu_active_runner" = "Активный Runner"
        "menu_path" = "Путь"
        
        # Общее
        "invalid_option" = "Неверная опция. Попробуйте снова."
        "press_enter" = "Нажмите Enter для продолжения"
        "goodbye" = "Спасибо за использование Octopus Runner Manager!"
        "cancelled" = "Отменено"
        "error" = "Ошибка"
        "success" = "Успешно"
        "warning" = "Предупреждение"
        "yes" = "да"
        "no" = "нет"
        
        # Платформа
        "platform_github" = "GitHub Actions"
        "platform_gitlab" = "GitLab CI/CD"
        "platform_selection_title" = "Выбор платформы"
        "platform_select_prompt" = "Выберите платформу:"
        "platform_invalid" = "Неверный выбор"
        
        # Тип цели
        "target_type_title" = "Выбор типа цели"
        "target_type_prompt" = "Выберите тип цели:"
        "target_type_project" = "Проект (один репозиторий)"
        "target_type_group" = "Группа (несколько проектов)"
        
        # Настройка токена
        "token_config_title" = "Настройка токена {0}"
        "token_config_help_github" = "Требуемые разрешения:"
        "token_config_perm_repo" = "repo (Полный контроль приватных репозиториев)"
        "token_config_perm_workflow" = "workflow (Обновление GitHub Action workflows)"
        "token_config_perm_api" = "api (Полный доступ к API)"
        "token_config_create_github" = "Создать токен: https://github.com/settings/tokens"
        "token_config_create_gitlab" = "Создать токен: {0}/-/profile/personal_access_tokens"
        "token_config_create_gitlab_self" = "Для self-hosted: https://your-gitlab.com/-/profile/personal_access_tokens"
        "token_current" = "Текущий токен"
        "token_update" = "Обновить токен? (y/n)"
        "token_enter" = "Введите ваш {0} токен"
        "token_saved" = "Токен успешно сохранен"
        
        # Хранение токена
        "token_storage_question" = "Как вы хотите сохранить токен?"
        "token_storage_env" = "Переменная окружения (постоянно, сохраняется после перезагрузки)"
        "token_storage_file" = "Зашифрованный файл (хранится в конфиге)"
        "token_storage_session" = "Только сессия (временно, теряется при выходе)"
        
        # Выбор репозитория
        "repo_selection_title" = "Выбор {0}"
        "repo_token_not_configured" = "Токен {0} не настроен"
        "repo_configure_token_first" = "Пожалуйста, сначала настройте токен (Опция 1)"
        "repo_fetching" = "Загрузка {0}..."
        "repo_projects" = "проектов"
        "repo_groups" = "групп"
        "repo_repositories" = "репозиториев"
        "repo_none_found" = "{0} не найдено"
        "repo_search_prompt" = "Поиск {0} (введите часть названия):"
        "repo_search" = "Поиск"
        "repo_no_match" = "Нет {0} соответствующих '{1}'"
        "repo_found" = "Найдено {0} {1}"
        "repo_select_prompt" = "Выберите {0} (1-{1})"
        "repo_set_to" = "{0} установлен на: {1}"
        "repo_error_fetching" = "Ошибка загрузки {0}: {1}"
        "repo_page_info" = "Страница {0} из {1} (Всего: {2} репозиториев)"
        "repo_visibility_private" = "[Приватный]"
        "repo_visibility_public" = "[Публичный]"
        "repo_commands" = "Команды:"
        "repo_cmd_select" = "[номер] - Выбрать репозиторий"
        "repo_cmd_next" = "n - Следующая страница"
        "repo_cmd_prev" = "p - Предыдущая страница"
        "repo_cmd_search" = "s - Поиск/Фильтр"
        "repo_cmd_clear" = "c - Очистить фильтр"
        "repo_cmd_quit" = "q - Выход"
        "repo_enter_command" = "Введите команду или номер"
        "repo_search_filter" = "Фильтр поиска: '{0}'"
        "repo_invalid_selection" = "Неверный выбор"
        "repo_last_page" = "Уже на последней странице"
        "repo_first_page" = "Уже на первой странице"
        "repo_enter_search" = "Введите поисковый запрос (поиск по названию и описанию)"
        "repo_no_match_found" = "Нет репозиториев соответствующих '{0}'"
        "repo_filter_cleared" = "Фильтр очищен"
        "repo_invalid_command" = "Неверная команда"
        "repo_fetching_repos" = "Загрузка ваших репозиториев..."
        
        # Статус Runner'а
        "status_title" = "Статус Runner'а"
        "status_repository" = "Репозиторий"
        "status_token" = "Токен"
        "status_installation" = "Установка"
        "status_installed_at" = "Установлен в {0}"
        "status_not_installed" = "Не установлен"
        "status_autostart" = "Автозапуск"
        "status_process" = "Процесс"
        "status_running_pid" = "Запущен (PID: {0})"
        "status_not_running" = "Не запущен"
        "status_running" = "запущено"
        
        # Мульти-Runner
        "multirunner_title" = "Управление несколькими Runner'ами"
        "multirunner_local_runners" = "Локальные Runner'ы"
        "multirunner_no_runners" = "Локальные runner'ы не настроены"
        "multirunner_tip" = "Совет: Используйте опцию 1 для добавления нового runner'а"
        "multirunner_add" = "Добавить новый runner"
        "multirunner_select" = "Выбрать активный runner"
        "multirunner_remove" = "Удалить runner"
        "multirunner_back" = "Назад в главное меню"
        "multirunner_add_title" = "Добавить новый локальный Runner"
        "multirunner_enter_name" = "Введите имя runner'а (например, 'Основной Runner', 'Резервный Runner'):"
        "multirunner_name" = "Имя"
        "multirunner_name_empty" = "Имя runner'а не может быть пустым"
        "multirunner_enter_path" = "Введите путь установки runner'а:"
        "multirunner_example" = "Пример"
        "multirunner_path" = "Путь"
        "multirunner_using_default" = "Используется путь по умолчанию: {0}"
        "multirunner_path_exists" = "Предупреждение: Путь уже существует. Runner может быть уже установлен."
        "multirunner_continue" = "Продолжить в любом случае? (y/n)"
        "multirunner_current_repo" = "Текущий репозиторий: {0}"
        "multirunner_use_current" = "Использовать текущий репозиторий? (y/n)"
        "multirunner_enter_repo" = "Введите репозиторий (owner/repo):"
        "multirunner_repo_empty" = "Репозиторий не может быть пустым"
        "multirunner_added" = "Runner успешно добавлен!"
        "multirunner_runner_id" = "ID Runner'а: {0}"
        "multirunner_next_steps" = "Следующие шаги:"
        "multirunner_step_select" = "Выберите этот runner как активный (опция 2)"
        "multirunner_step_install" = "Установите runner (опция 5 в главном меню)"
        "multirunner_select_title" = "Выбрать активный Runner"
        "multirunner_no_runners_add" = "Runner'ы не настроены. Сначала добавьте runner."
        "multirunner_cancel" = "Отмена"
        "multirunner_invalid_selection" = "Неверный выбор"
        "multirunner_active_set" = "Активный runner установлен на: {0}"
        "multirunner_remove_title" = "Удалить локальный Runner"
        "multirunner_remove_warning" = "Предупреждение: Это удалит конфигурацию runner'а"
        "multirunner_remove_files_kept" = "Файлы runner'а в {0} НЕ будут удалены"
        "multirunner_confirm" = "Вы уверены? (yes/no)"
        "multirunner_removed" = "Runner удален из конфигурации"
        
        # Docker
        "docker_title" = "Управление Docker контейнерами"
        "docker_not_installed" = "Docker не установлен или не в PATH"
        "docker_install_prompt" = "Пожалуйста, установите Docker Desktop: https://www.docker.com/products/docker-desktop"
        "docker_not_running" = "Docker daemon не запущен"
        "docker_start_prompt" = "Пожалуйста, запустите Docker Desktop и попробуйте снова"
        "docker_checking" = "Проверка статуса Docker..."
        "docker_available" = "Docker доступен"
        
        # Telegram
        "telegram_config_title" = "Настройка уведомлений Telegram"
        "telegram_current_status" = "Текущий статус:"
        "telegram_status_enabled" = "ВКЛЮЧЕНО"
        "telegram_status_disabled" = "ОТКЛЮЧЕНО"
        "telegram_registered_users" = "Зарегистрировано пользователей: {0}"
        "telegram_option_enable" = "Включить/Настроить уведомления Telegram"
        "telegram_option_add_user" = "Добавить пользователя (Chat ID)"
        "telegram_option_remove_user" = "Удалить пользователя"
        "telegram_option_test" = "Тестовое уведомление"
        "telegram_option_disable" = "Отключить уведомления"
        "telegram_option_back" = "Назад"
        "telegram_enter_token" = "Введите токен Telegram бота"
        "telegram_bot_connected" = "Бот подключен: @{0}"
        "telegram_failed_connect" = "Не удалось подключиться к Telegram боту: {0}"
        "telegram_getting_chat_ids" = "Получение доступных Chat ID..."
        "telegram_found_chat_ids" = "Найдены Chat ID: {0}"
        "telegram_add_all_chats" = "Добавить все найденные Chat ID? (y/n)"
        "telegram_enabled" = "Уведомления Telegram включены!"
        "telegram_configure_first" = "Пожалуйста, сначала настройте Telegram бота (опция 1)"
        "telegram_enter_chat_id" = "Введите Chat ID для добавления"
        "telegram_user_added" = "Пользователь успешно добавлен!"
        "telegram_user_exists" = "Этот пользователь уже зарегистрирован"
        "telegram_no_users" = "Нет зарегистрированных пользователей"
        "telegram_registered_users_list" = "Зарегистрированные пользователи:"
        "telegram_enter_number_remove" = "Введите номер для удаления"
        "telegram_user_removed" = "Пользователь успешно удален!"
        "telegram_not_configured" = "Уведомления Telegram не настроены"
        "telegram_sending_test" = "Отправка тестового уведомления..."
        "telegram_test_success" = "Успешно отправлено в {0} из {1} чатов"
        "telegram_test_failed" = "Не удалось отправить во все чаты"
        "telegram_failed_chats" = "Неудачные чаты:"
        "telegram_chat_id" = "Chat ID: {0}"
        "telegram_common_issues" = "Распространенные проблемы:"
        "telegram_issue_not_started" = "Пользователь не начал разговор с ботом"
        "telegram_solution_start" = "Решение: Откройте Telegram, найдите вашего бота, нажмите START"
        "telegram_issue_blocked" = "Пользователь заблокировал бота"
        "telegram_solution_unblock" = "Решение: Разблокируйте бота в настройках Telegram"
        "telegram_issue_invalid_id" = "Неверный Chat ID"
        "telegram_solution_get_id" = "Решение: Получите правильный Chat ID от @userinfobot"
        "telegram_disabled" = "Уведомления Telegram отключены"
        "telegram_how_to_get_id" = "Как получить ваш Telegram Chat ID"
        "telegram_method_userinfobot" = "Метод 1: Используя @userinfobot"
        "telegram_step_search" = "Откройте Telegram и найдите @userinfobot"
        "telegram_step_start" = "Начните разговор и отправьте /start"
        "telegram_step_reply" = "Бот ответит с вашим Chat ID"
        "telegram_method_auto" = "Метод 2: Автоматическое определение"
        "telegram_step_send_message" = "Отправьте любое сообщение вашему боту"
        "telegram_step_detect" = "Этот инструмент определит ваш Chat ID"
        "telegram_checking_messages" = "Проверка сообщений..."
        "telegram_found_chats" = "Найдено {0} чат(ов):"
        "telegram_username" = "Имя пользователя: @{0}"
        "telegram_name" = "Имя: {0}"
        "telegram_type" = "Тип: {0}"
        "telegram_no_messages" = "Сообщения не найдены."
        "telegram_send_message_prompt" = "Пожалуйста, отправьте сообщение вашему боту и попробуйте снова."
        "telegram_error_getting_ids" = "Не удалось получить Chat ID: {0}"
    }
}

function Get-Translation {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Key,
        
        [Parameter(Mandatory=$false, ValueFromRemainingArguments=$true)]
        [object[]]$Params
    )
    
    $lang = $script:CurrentLanguage
    
    if ($script:Translations.ContainsKey($lang) -and $script:Translations[$lang].ContainsKey($Key)) {
        $text = $script:Translations[$lang][$Key]
        if ($Params -and $Params.Count -gt 0) {
            return $text -f $Params
        }
        return $text
    }
    
    # Fallback to English
    if ($script:Translations["en"].ContainsKey($Key)) {
        $text = $script:Translations["en"][$Key]
        if ($Params -and $Params.Count -gt 0) {
            return $text -f $Params
        }
        return $text
    }
    
    # Return key if not found
    return $Key
}

function Set-Language {
    param(
        [Parameter(Mandatory=$true)]
        [ValidateSet("en", "ru")]
        [string]$Language
    )
    
    $script:CurrentLanguage = $Language
}

function Get-CurrentLanguage {
    return $script:CurrentLanguage
}

function Get-AvailableLanguages {
    return @("en", "ru")
}

# Alias for shorter usage
Set-Alias -Name L -Value Get-Translation -Scope Global


# Additional translations for menu items
$script:Translations["en"]["menu_configuration"] = "Configuration"
$script:Translations["en"]["menu_configure_token"] = "Configure {0} Token"
$script:Translations["en"]["menu_select_repository"] = "Select Repository"
$script:Translations["en"]["menu_select_project_group"] = "Select Project/Group"
$script:Translations["en"]["menu_configure_secrets"] = "Configure GitHub Secrets (Auto)"
$script:Translations["en"]["menu_configure_instance"] = "Configure Instance URL"
$script:Translations["en"]["menu_switch_platform"] = "Switch Platform (GitHub / GitLab)"
$script:Translations["en"]["menu_runner_management"] = "Runner Management"
$script:Translations["en"]["menu_install_runner"] = "Install Runner"
$script:Translations["en"]["menu_start_runner"] = "Start Runner"
$script:Translations["en"]["menu_stop_runner"] = "Stop Runner"
$script:Translations["en"]["menu_check_status"] = "Check Status"
$script:Translations["en"]["menu_view_logs"] = "View Logs"
$script:Translations["en"]["menu_view_active_runners"] = "View Active Runners"
$script:Translations["en"]["menu_autostart"] = "Auto-Start"
$script:Translations["en"]["menu_enable_autostart"] = "Enable Auto-Start (on boot)"
$script:Translations["en"]["menu_disable_autostart"] = "Disable Auto-Start"
$script:Translations["en"]["menu_advanced"] = "Advanced"
$script:Translations["en"]["menu_uninstall_runner"] = "Uninstall Runner"
$script:Translations["en"]["menu_clear_config"] = "Clear Configuration"
$script:Translations["en"]["menu_infrastructure"] = "Infrastructure Suite"
$script:Translations["en"]["menu_telegram"] = "Telegram Notifications"
$script:Translations["en"]["menu_docker"] = "Docker Container Management"
$script:Translations["en"]["menu_multirunner"] = "Multi-Runner Management"
$script:Translations["en"]["menu_help"] = "Help and Quick Start Guide"
$script:Translations["en"]["menu_language"] = "Language / Язык"
$script:Translations["en"]["menu_exit"] = "Exit"
$script:Translations["en"]["menu_select_option"] = "Select option"

$script:Translations["ru"]["menu_configuration"] = "Конфигурация"
$script:Translations["ru"]["menu_configure_token"] = "Настроить токен {0}"
$script:Translations["ru"]["menu_select_repository"] = "Выбрать репозиторий"
$script:Translations["ru"]["menu_select_project_group"] = "Выбрать проект/группу"
$script:Translations["ru"]["menu_configure_secrets"] = "Настроить GitHub Secrets (Авто)"
$script:Translations["ru"]["menu_configure_instance"] = "Настроить URL инстанса"
$script:Translations["ru"]["menu_switch_platform"] = "Сменить платформу (GitHub / GitLab)"
$script:Translations["ru"]["menu_runner_management"] = "Управление Runner'ами"
$script:Translations["ru"]["menu_install_runner"] = "Установить Runner"
$script:Translations["ru"]["menu_start_runner"] = "Запустить Runner"
$script:Translations["ru"]["menu_stop_runner"] = "Остановить Runner"
$script:Translations["ru"]["menu_check_status"] = "Проверить статус"
$script:Translations["ru"]["menu_view_logs"] = "Просмотр логов"
$script:Translations["ru"]["menu_view_active_runners"] = "Просмотр активных Runner'ов"
$script:Translations["ru"]["menu_autostart"] = "Автозапуск"
$script:Translations["ru"]["menu_enable_autostart"] = "Включить автозапуск (при загрузке)"
$script:Translations["ru"]["menu_disable_autostart"] = "Отключить автозапуск"
$script:Translations["ru"]["menu_advanced"] = "Дополнительно"
$script:Translations["ru"]["menu_uninstall_runner"] = "Удалить Runner"
$script:Translations["ru"]["menu_clear_config"] = "Очистить конфигурацию"
$script:Translations["ru"]["menu_infrastructure"] = "Инфраструктурный набор"
$script:Translations["ru"]["menu_telegram"] = "Telegram уведомления"
$script:Translations["ru"]["menu_docker"] = "Управление Docker контейнерами"
$script:Translations["ru"]["menu_multirunner"] = "Управление несколькими Runner'ами"
$script:Translations["ru"]["menu_help"] = "Справка и быстрый старт"
$script:Translations["ru"]["menu_language"] = "Язык / Language"
$script:Translations["ru"]["menu_exit"] = "Выход"
$script:Translations["ru"]["menu_select_option"] = "Выберите опцию"


# Banner and status translations
$script:Translations["en"]["banner_title"] = "OCTOPUS RUNNER MANAGER"
$script:Translations["en"]["banner_subtitle"] = "Advanced CI/CD Infrastructure Suite"
$script:Translations["en"]["banner_powered"] = "Powered by"

$script:Translations["ru"]["banner_title"] = "OCTOPUS RUNNER MANAGER"
$script:Translations["ru"]["banner_subtitle"] = "Продвинутый набор CI/CD инфраструктуры"
$script:Translations["ru"]["banner_powered"] = "Разработано"

# Status display translations
$script:Translations["en"]["status_platform"] = "Platform"
$script:Translations["en"]["status_instance"] = "Instance"
$script:Translations["en"]["status_repository"] = "Repository"
$script:Translations["en"]["status_token"] = "Token"
$script:Translations["en"]["status_telegram"] = "Telegram"
$script:Translations["en"]["status_docker"] = "Docker"
$script:Translations["en"]["status_local_runners"] = "Local Runners"
$script:Translations["en"]["status_active_runner"] = "Active Runner"
$script:Translations["en"]["status_path"] = "Path"
$script:Translations["en"]["status_configured"] = "Configured"
$script:Translations["en"]["status_not_configured"] = "Not configured"
$script:Translations["en"]["status_enabled"] = "Enabled"
$script:Translations["en"]["status_disabled"] = "Disabled"
$script:Translations["en"]["status_containers"] = "container(s)"
$script:Translations["en"]["status_runners_configured"] = "configured"

$script:Translations["ru"]["status_platform"] = "Платформа"
$script:Translations["ru"]["status_instance"] = "Инстанс"
$script:Translations["ru"]["status_repository"] = "Репозиторий"
$script:Translations["ru"]["status_token"] = "Токен"
$script:Translations["ru"]["status_telegram"] = "Telegram"
$script:Translations["ru"]["status_docker"] = "Docker"
$script:Translations["ru"]["status_local_runners"] = "Локальные Runner'ы"
$script:Translations["ru"]["status_active_runner"] = "Активный Runner"
$script:Translations["ru"]["status_path"] = "Путь"
$script:Translations["ru"]["status_configured"] = "Настроен"
$script:Translations["ru"]["status_not_configured"] = "Не настроено"
$script:Translations["ru"]["status_enabled"] = "Включен"
$script:Translations["ru"]["status_disabled"] = "Отключен"
$script:Translations["ru"]["status_containers"] = "контейнер(ов)"
$script:Translations["ru"]["status_runners_configured"] = "настроено"


# Exit messages
$script:Translations["en"]["goodbye_message"] = "Thank you for using Octopus Runner Manager!"
$script:Translations["en"]["goodbye_powered"] = "Powered by"

$script:Translations["ru"]["goodbye_message"] = "Спасибо за использование Octopus Runner Manager!"
$script:Translations["ru"]["goodbye_powered"] = "Разработано"


# Help Guide translations
$script:Translations["en"]["help_title"] = "QUICK START GUIDE"
$script:Translations["en"]["help_first_setup"] = "FIRST TIME SETUP"
$script:Translations["en"]["help_step1"] = "Configure Token (Option 1)"
$script:Translations["en"]["help_step1_detail1"] = "Get token from: https://github.com/settings/tokens"
$script:Translations["en"]["help_step1_detail2"] = "Required scopes: repo, workflow"
$script:Translations["en"]["help_step2"] = "Select Repository (Option 2)"
$script:Translations["en"]["help_step2_detail"] = "Search and select your repository"
$script:Translations["en"]["help_step3"] = "Install Runner (Option 5)"
$script:Translations["en"]["help_step3_detail"] = "Downloads and configures runner"
$script:Translations["en"]["help_step4"] = "Start Runner (Option 6)"
$script:Translations["en"]["help_step4_detail"] = "Starts the runner process"
$script:Translations["en"]["help_docker"] = "DOCKER RUNNERS"
$script:Translations["en"]["help_docker_menu"] = "Option 16 → Docker Container Management"
$script:Translations["en"]["help_docker_build"] = "Option 1: Build runner image"
$script:Translations["en"]["help_docker_build_detail"] = "Creates Docker image with Node.js, PHP, Composer"
$script:Translations["en"]["help_docker_start"] = "Option 2: Start new container"
$script:Translations["en"]["help_docker_start_detail"] = "Launches isolated runner in Docker"
$script:Translations["en"]["help_docker_rebuild"] = "Option 8: Rebuild and restart (recommended)"
$script:Translations["en"]["help_docker_rebuild_detail1"] = "Auto-updates to latest runner version"
$script:Translations["en"]["help_docker_rebuild_detail2"] = "Cleans up old offline runners"
$script:Translations["en"]["help_docker_restart"] = "Option 9: Quick restart"
$script:Translations["en"]["help_docker_restart_detail"] = "Fast restart without rebuild"
$script:Translations["en"]["help_docker_health"] = "Option 10: Health check"
$script:Translations["en"]["help_docker_health_detail"] = "Diagnose runner issues"
$script:Translations["en"]["help_docker_cleanup"] = "Option 11: Cleanup offline runners"
$script:Translations["en"]["help_docker_cleanup_detail"] = "Remove dead runners from GitHub"
$script:Translations["en"]["help_tips"] = "TIPS AND TRICKS"
$script:Translations["en"]["help_tip_search"] = "Partial container search:"
$script:Translations["en"]["help_tip_search_detail"] = "Type 'avyx' instead of full ID '0d81c0b7d764...'"
$script:Translations["en"]["help_tip_autostart"] = "Auto-start on boot:"
$script:Translations["en"]["help_tip_autostart_detail"] = "Use Option 11 to enable automatic runner start"
$script:Translations["en"]["help_tip_telegram"] = "Telegram notifications:"
$script:Translations["en"]["help_tip_telegram_detail"] = "Option 15 to get alerts about runner events"
$script:Translations["en"]["help_tip_multiple"] = "Multiple runners:"
$script:Translations["en"]["help_tip_multiple_detail"] = "Option 16 → 7 for bulk deployment"
$script:Translations["en"]["help_troubleshooting"] = "TROUBLESHOOTING"
$script:Translations["en"]["help_trouble_stuck"] = "Runner stuck or offline?"
$script:Translations["en"]["help_trouble_stuck_fix"] = "→ Option 16 → 9 (Quick restart)"
$script:Translations["en"]["help_trouble_queuing"] = "Jobs queuing but not running?"
$script:Translations["en"]["help_trouble_queuing_fix1"] = "→ Option 16 → 10 (Health check)"
$script:Translations["en"]["help_trouble_queuing_fix2"] = "→ Option 16 → 8 (Rebuild with latest version)"
$script:Translations["en"]["help_trouble_accumulating"] = "Old runners accumulating?"
$script:Translations["en"]["help_trouble_accumulating_fix"] = "→ Option 16 → 11 (Cleanup offline runners)"
$script:Translations["en"]["help_documentation"] = "DOCUMENTATION"
$script:Translations["en"]["help_press_enter"] = "Press Enter to return to main menu"

$script:Translations["ru"]["help_title"] = "РУКОВОДСТВО ПО БЫСТРОМУ СТАРТУ"
$script:Translations["ru"]["help_first_setup"] = "ПЕРВОНАЧАЛЬНАЯ НАСТРОЙКА"
$script:Translations["ru"]["help_step1"] = "Настроить токен (Опция 1)"
$script:Translations["ru"]["help_step1_detail1"] = "Получить токен: https://github.com/settings/tokens"
$script:Translations["ru"]["help_step1_detail2"] = "Требуемые разрешения: repo, workflow"
$script:Translations["ru"]["help_step2"] = "Выбрать репозиторий (Опция 2)"
$script:Translations["ru"]["help_step2_detail"] = "Найти и выбрать ваш репозиторий"
$script:Translations["ru"]["help_step3"] = "Установить Runner (Опция 5)"
$script:Translations["ru"]["help_step3_detail"] = "Загружает и настраивает runner"
$script:Translations["ru"]["help_step4"] = "Запустить Runner (Опция 6)"
$script:Translations["ru"]["help_step4_detail"] = "Запускает процесс runner'а"
$script:Translations["ru"]["help_docker"] = "DOCKER RUNNER'Ы"
$script:Translations["ru"]["help_docker_menu"] = "Опция 16 → Управление Docker контейнерами"
$script:Translations["ru"]["help_docker_build"] = "Опция 1: Собрать образ runner'а"
$script:Translations["ru"]["help_docker_build_detail"] = "Создает Docker образ с Node.js, PHP, Composer"
$script:Translations["ru"]["help_docker_start"] = "Опция 2: Запустить новый контейнер"
$script:Translations["ru"]["help_docker_start_detail"] = "Запускает изолированный runner в Docker"
$script:Translations["ru"]["help_docker_rebuild"] = "Опция 8: Пересобрать и перезапустить (рекомендуется)"
$script:Translations["ru"]["help_docker_rebuild_detail1"] = "Автоматически обновляет до последней версии runner'а"
$script:Translations["ru"]["help_docker_rebuild_detail2"] = "Очищает старые оффлайн runner'ы"
$script:Translations["ru"]["help_docker_restart"] = "Опция 9: Быстрый перезапуск"
$script:Translations["ru"]["help_docker_restart_detail"] = "Быстрый перезапуск без пересборки"
$script:Translations["ru"]["help_docker_health"] = "Опция 10: Проверка здоровья"
$script:Translations["ru"]["help_docker_health_detail"] = "Диагностика проблем runner'а"
$script:Translations["ru"]["help_docker_cleanup"] = "Опция 11: Очистка оффлайн runner'ов"
$script:Translations["ru"]["help_docker_cleanup_detail"] = "Удаление мертвых runner'ов из GitHub"
$script:Translations["ru"]["help_tips"] = "СОВЕТЫ И ХИТРОСТИ"
$script:Translations["ru"]["help_tip_search"] = "Частичный поиск контейнера:"
$script:Translations["ru"]["help_tip_search_detail"] = "Введите 'avyx' вместо полного ID '0d81c0b7d764...'"
$script:Translations["ru"]["help_tip_autostart"] = "Автозапуск при загрузке:"
$script:Translations["ru"]["help_tip_autostart_detail"] = "Используйте Опцию 11 для включения автоматического запуска runner'а"
$script:Translations["ru"]["help_tip_telegram"] = "Telegram уведомления:"
$script:Translations["ru"]["help_tip_telegram_detail"] = "Опция 15 для получения уведомлений о событиях runner'а"
$script:Translations["ru"]["help_tip_multiple"] = "Несколько runner'ов:"
$script:Translations["ru"]["help_tip_multiple_detail"] = "Опция 16 → 7 для массового развертывания"
$script:Translations["ru"]["help_troubleshooting"] = "УСТРАНЕНИЕ НЕПОЛАДОК"
$script:Translations["ru"]["help_trouble_stuck"] = "Runner завис или оффлайн?"
$script:Translations["ru"]["help_trouble_stuck_fix"] = "→ Опция 16 → 9 (Быстрый перезапуск)"
$script:Translations["ru"]["help_trouble_queuing"] = "Задачи в очереди, но не выполняются?"
$script:Translations["ru"]["help_trouble_queuing_fix1"] = "→ Опция 16 → 10 (Проверка здоровья)"
$script:Translations["ru"]["help_trouble_queuing_fix2"] = "→ Опция 16 → 8 (Пересборка с последней версией)"
$script:Translations["ru"]["help_trouble_accumulating"] = "Накапливаются старые runner'ы?"
$script:Translations["ru"]["help_trouble_accumulating_fix"] = "→ Опция 16 → 11 (Очистка оффлайн runner'ов)"
$script:Translations["ru"]["help_documentation"] = "ДОКУМЕНТАЦИЯ"
$script:Translations["ru"]["help_press_enter"] = "Нажмите Enter для возврата в главное меню"


# Multi-Runner Management translations
$script:Translations["en"]["multirunner_title"] = "Multi-Runner Management"
$script:Translations["en"]["multirunner_local_title"] = "Local Runners (Windows)"
$script:Translations["en"]["multirunner_no_runners"] = "No local runners configured"
$script:Translations["en"]["multirunner_tip"] = "Tip: Use option 1 to add a new runner"
$script:Translations["en"]["multirunner_note_local"] = "Note: Local runners run directly on Windows."
$script:Translations["en"]["multirunner_note_docker"] = "Docker runners are managed separately (Main Menu → Option 16)"
$script:Translations["en"]["multirunner_docker_note"] = "Docker Runners: Managed separately (Main Menu → Option 16)"
$script:Translations["en"]["multirunner_type"] = "Type"
$script:Translations["en"]["multirunner_type_local"] = "Local (Windows)"
$script:Translations["en"]["multirunner_id"] = "ID"
$script:Translations["en"]["multirunner_repository"] = "Repository"
$script:Translations["en"]["multirunner_path"] = "Path"
$script:Translations["en"]["multirunner_platform"] = "Platform"
$script:Translations["en"]["multirunner_status"] = "Status"
$script:Translations["en"]["multirunner_pid"] = "PID"
$script:Translations["en"]["multirunner_uptime"] = "Uptime"
$script:Translations["en"]["multirunner_status_running"] = "Running"
$script:Translations["en"]["multirunner_status_stopped"] = "Stopped"
$script:Translations["en"]["multirunner_status_not_installed"] = "Not Installed"
$script:Translations["en"]["multirunner_option_add"] = "Add new runner"
$script:Translations["en"]["multirunner_option_select"] = "Select active runner"
$script:Translations["en"]["multirunner_option_remove"] = "Remove runner"
$script:Translations["en"]["multirunner_option_back"] = "Back to main menu"

$script:Translations["ru"]["multirunner_title"] = "Управление несколькими Runner'ами"
$script:Translations["ru"]["multirunner_local_title"] = "Локальные Runner'ы (Windows)"
$script:Translations["ru"]["multirunner_no_runners"] = "Локальные runner'ы не настроены"
$script:Translations["ru"]["multirunner_tip"] = "Совет: Используйте опцию 1 для добавления нового runner'а"
$script:Translations["ru"]["multirunner_note_local"] = "Примечание: Локальные runner'ы запускаются напрямую на Windows."
$script:Translations["ru"]["multirunner_note_docker"] = "Docker runner'ы управляются отдельно (Главное меню → Опция 16)"
$script:Translations["ru"]["multirunner_docker_note"] = "Docker Runner'ы: Управляются отдельно (Главное меню → Опция 16)"
$script:Translations["ru"]["multirunner_type"] = "Тип"
$script:Translations["ru"]["multirunner_type_local"] = "Локальный (Windows)"
$script:Translations["ru"]["multirunner_id"] = "ID"
$script:Translations["ru"]["multirunner_repository"] = "Репозиторий"
$script:Translations["ru"]["multirunner_path"] = "Путь"
$script:Translations["ru"]["multirunner_platform"] = "Платформа"
$script:Translations["ru"]["multirunner_status"] = "Статус"
$script:Translations["ru"]["multirunner_pid"] = "PID"
$script:Translations["ru"]["multirunner_uptime"] = "Время работы"
$script:Translations["ru"]["multirunner_status_running"] = "Запущен"
$script:Translations["ru"]["multirunner_status_stopped"] = "Остановлен"
$script:Translations["ru"]["multirunner_status_not_installed"] = "Не установлен"
$script:Translations["ru"]["multirunner_option_add"] = "Добавить новый runner"
$script:Translations["ru"]["multirunner_option_select"] = "Выбрать активный runner"
$script:Translations["ru"]["multirunner_option_remove"] = "Удалить runner"
$script:Translations["ru"]["multirunner_option_back"] = "Назад в главное меню"


# Docker Container Management translations
$script:Translations["en"]["docker_menu_title"] = "Docker Container Management"
$script:Translations["en"]["docker_option_build"] = "Build runner image"
$script:Translations["en"]["docker_option_start"] = "Start new runner container"
$script:Translations["en"]["docker_option_list"] = "List running containers"
$script:Translations["en"]["docker_option_stop"] = "Stop container"
$script:Translations["en"]["docker_option_remove"] = "Remove container"
$script:Translations["en"]["docker_option_logs"] = "View container logs"
$script:Translations["en"]["docker_option_bulk"] = "Bulk deploy (multiple containers)"
$script:Translations["en"]["docker_option_rebuild"] = "Rebuild and restart runner (auto)"
$script:Translations["en"]["docker_option_restart"] = "Restart container (quick fix)"
$script:Translations["en"]["docker_option_health"] = "Health check"
$script:Translations["en"]["docker_option_cleanup"] = "Cleanup offline runners from GitHub"
$script:Translations["en"]["docker_option_back"] = "Back"

$script:Translations["ru"]["docker_menu_title"] = "Управление Docker контейнерами"
$script:Translations["ru"]["docker_option_build"] = "Собрать образ runner'а"
$script:Translations["ru"]["docker_option_start"] = "Запустить новый контейнер runner'а"
$script:Translations["ru"]["docker_option_list"] = "Список запущенных контейнеров"
$script:Translations["ru"]["docker_option_stop"] = "Остановить контейнер"
$script:Translations["ru"]["docker_option_remove"] = "Удалить контейнер"
$script:Translations["ru"]["docker_option_logs"] = "Просмотр логов контейнера"
$script:Translations["ru"]["docker_option_bulk"] = "Массовое развертывание (несколько контейнеров)"
$script:Translations["ru"]["docker_option_rebuild"] = "Пересобрать и перезапустить runner (авто)"
$script:Translations["ru"]["docker_option_restart"] = "Перезапустить контейнер (быстрое исправление)"
$script:Translations["ru"]["docker_option_health"] = "Проверка здоровья"
$script:Translations["ru"]["docker_option_cleanup"] = "Очистка оффлайн runner'ов из GitHub"
$script:Translations["ru"]["docker_option_back"] = "Назад"


# Secrets Manager translations
$script:Translations["en"]["secrets_testing_ssh"] = "Testing SSH connection to {0}@{1}:{2}..."
$script:Translations["en"]["secrets_ssh_port_ok"] = "SSH port is accessible"
$script:Translations["en"]["secrets_ssh_port_fail"] = "Cannot connect to SSH server"
$script:Translations["en"]["secrets_check_list"] = "Please check:"
$script:Translations["en"]["secrets_check_host"] = "Host IP/hostname is correct: {0}"
$script:Translations["en"]["secrets_check_port"] = "Port is correct: {0}"
$script:Translations["en"]["secrets_check_server"] = "SSH server is running"
$script:Translations["en"]["secrets_check_firewall"] = "Firewall allows connections"
$script:Translations["en"]["secrets_checking_keys"] = "Checking for existing SSH keys..."
$script:Translations["en"]["secrets_ssh_success_keys"] = "SSH connection successful (using existing keys)"
$script:Translations["en"]["secrets_note_keys_exist"] = "Note: You already have SSH keys configured for this server"
$script:Translations["en"]["secrets_password_not_needed"] = "Password authentication may not be needed"
$script:Translations["en"]["secrets_auto_test_unreliable"] = "Automated password testing is not reliable on Windows"
$script:Translations["en"]["secrets_verify_manually"] = "Please verify manually:"
$script:Translations["en"]["secrets_run_command"] = "Run this command: ssh {0}@{1}"
$script:Translations["en"]["secrets_can_connect"] = "Can you connect manually with this command? (y/N)"
$script:Translations["en"]["secrets_manual_verify_ok"] = "Manual verification successful"
$script:Translations["en"]["secrets_creds_saved"] = "Credentials will be saved to GitHub Secrets"
$script:Translations["en"]["secrets_verify_creds"] = "Please verify your credentials"
$script:Translations["en"]["secrets_check"] = "Check:"
$script:Translations["en"]["secrets_host"] = "Host: {0}"
$script:Translations["en"]["secrets_port"] = "Port: {0}"
$script:Translations["en"]["secrets_username"] = "Username: {0}"
$script:Translations["en"]["secrets_password_hidden"] = "Password: (hidden)"
$script:Translations["en"]["secrets_error_testing"] = "Error testing connection: {0}"
$script:Translations["en"]["secrets_note_limited"] = "Note: Automated SSH testing is limited on Windows"
$script:Translations["en"]["secrets_if_manual_ok"] = "If you can connect manually with 'ssh {0}@{1}', the credentials are correct"
$script:Translations["en"]["secrets_ssh_setup_title"] = "=== SSH Key Setup ==="
$script:Translations["en"]["secrets_generating_key"] = "Generating SSH key pair..."
$script:Translations["en"]["secrets_key_generated"] = "SSH key pair generated"
$script:Translations["en"]["secrets_key_gen_failed"] = "Failed to generate SSH key"
$script:Translations["en"]["secrets_using_existing"] = "Using existing SSH key: {0}"
$script:Translations["en"]["secrets_copying_key"] = "Copying public key to server..."
$script:Translations["en"]["secrets_key_copied"] = "Public key copied to server"
$script:Translations["en"]["secrets_saving_private"] = "Saving private key to GitHub secret..."
$script:Translations["en"]["secrets_private_key_ok"] = "SSH_PRIVATE_KEY configured"
$script:Translations["en"]["secrets_setup_complete"] = "SSH key setup complete!"
$script:Translations["en"]["secrets_passwordless"] = "You can now use passwordless SSH authentication"
$script:Translations["en"]["secrets_note_remove_pass"] = "Note: You may want to remove SSH_PASSWORD secret if using keys only"
$script:Translations["en"]["secrets_key_copy_failed"] = "Failed to copy public key to server"
$script:Translations["en"]["secrets_manual_copy"] = "You can manually copy the key:"
$script:Translations["en"]["secrets_pubkey_location"] = "Public key location: {0}"
$script:Translations["en"]["secrets_on_server_run"] = "On the server, run:"
$script:Translations["en"]["secrets_pubkey_not_found"] = "Public key file not found"
$script:Translations["en"]["secrets_chatid_title"] = "=== How to get Telegram Chat ID ==="
$script:Translations["en"]["secrets_chatid_step1"] = "1. Open @userinfobot in Telegram"
$script:Translations["en"]["secrets_chatid_step2"] = "2. Send /start command"
$script:Translations["en"]["secrets_chatid_step3"] = "3. Copy your ID (number, e.g.: 123456789)"
$script:Translations["en"]["secrets_chatid_group"] = "Or for a group:"
$script:Translations["en"]["secrets_chatid_group1"] = "1. Add @userinfobot to the group"
$script:Translations["en"]["secrets_chatid_group2"] = "2. Group ID starts with minus (e.g.: -100123456789)"
$script:Translations["en"]["secrets_gh_not_installed"] = "GitHub CLI (gh) is not installed"
$script:Translations["en"]["secrets_gh_required"] = "GitHub CLI is required for automatic secrets configuration."
$script:Translations["en"]["secrets_install_now"] = "Install now? (requires winget)"
$script:Translations["en"]["secrets_install_yes"] = "1. Yes, install via winget"
$script:Translations["en"]["secrets_install_manual"] = "2. No, I'll install manually"
$script:Translations["en"]["secrets_install_cancel"] = "3. Cancel"
$script:Translations["en"]["secrets_select_option"] = "Select option (1-3)"
$script:Translations["en"]["secrets_installing_gh"] = "Installing GitHub CLI..."
$script:Translations["en"]["secrets_gh_installed"] = "GitHub CLI installed"
$script:Translations["en"]["secrets_restart_script"] = "Restart the script to apply changes"
$script:Translations["en"]["secrets_install_error"] = "Installation error: {0}"
$script:Translations["en"]["secrets_install_manual_msg"] = "Install GitHub CLI manually:"
$script:Translations["en"]["secrets_or_via_winget"] = "Or via winget:"
$script:Translations["en"]["secrets_authenticating"] = "Authenticating with GitHub CLI..."
$script:Translations["en"]["secrets_auth_success"] = "Authentication successful"
$script:Translations["en"]["secrets_auth_failed"] = "Authentication failed"
$script:Translations["en"]["secrets_error"] = "Error: {0}"
$script:Translations["en"]["secrets_config_title"] = "=== GitHub Secrets Configuration ==="
$script:Translations["en"]["secrets_repository"] = "Repository: {0}"
$script:Translations["en"]["secrets_will_configure"] = "The following secrets will be configured:"
$script:Translations["en"]["secrets_ssh_host_desc"] = "1. SSH_HOST - server IP address"
$script:Translations["en"]["secrets_ssh_port_desc"] = "2. SSH_PORT - SSH port (default: 22)"
$script:Translations["en"]["secrets_ssh_user_desc"] = "3. SSH_USER - SSH username"
$script:Translations["en"]["secrets_ssh_pass_desc"] = "4. SSH_PASSWORD - SSH password"
$script:Translations["en"]["secrets_tg_token_desc"] = "5. TELEGRAM_BOT_TOKEN - Telegram bot token"
$script:Translations["en"]["secrets_tg_chat_desc"] = "6. TELEGRAM_ADMIN_CHAT_ID - your Telegram Chat ID"
$script:Translations["en"]["secrets_continue"] = "Continue? (y/N)"
$script:Translations["en"]["secrets_cancelled"] = "Cancelled"
$script:Translations["en"]["secrets_step_ssh_host"] = "[1/6] SSH_HOST"
$script:Translations["en"]["secrets_enter_host"] = "Enter server IP address or hostname"
$script:Translations["en"]["secrets_example_host"] = "Example: 192.168.1.100 or server.example.com"
$script:Translations["en"]["secrets_host_label"] = "Host"
$script:Translations["en"]["secrets_skipped"] = "Skipped"
$script:Translations["en"]["secrets_saving"] = "Saving {0}..."
$script:Translations["en"]["secrets_configured"] = "{0} configured"
$script:Translations["en"]["secrets_step_ssh_port"] = "[2/6] SSH_PORT"
$script:Translations["en"]["secrets_enter_port"] = "Enter SSH port (press Enter for default 22)"
$script:Translations["en"]["secrets_port_label"] = "Port"
$script:Translations["en"]["secrets_step_ssh_user"] = "[3/6] SSH_USER"
$script:Translations["en"]["secrets_enter_user"] = "Enter SSH username"
$script:Translations["en"]["secrets_example_user"] = "Example: root, ubuntu, admin"
$script:Translations["en"]["secrets_user_label"] = "Username"
$script:Translations["en"]["secrets_step_ssh_pass"] = "[4/6] SSH_PASSWORD"
$script:Translations["en"]["secrets_enter_pass"] = "Enter SSH password"
$script:Translations["en"]["secrets_pass_label"] = "Password"
$script:Translations["en"]["secrets_test_title"] = "=== SSH Connection Test ==="
$script:Translations["en"]["secrets_test_now"] = "Test SSH connection now? (y/N)"
$script:Translations["en"]["secrets_setup_keys_title"] = "=== SSH Key Setup ==="
$script:Translations["en"]["secrets_setup_keys_question"] = "Would you like to set up passwordless SSH access using SSH keys?"
$script:Translations["en"]["secrets_setup_keys_will"] = "This will:"
$script:Translations["en"]["secrets_setup_keys_step1"] = "1. Generate SSH key pair (if not exists)"
$script:Translations["en"]["secrets_setup_keys_step2"] = "2. Copy public key to server"
$script:Translations["en"]["secrets_setup_keys_step3"] = "3. Configure SSH_PRIVATE_KEY secret for GitHub Actions"
$script:Translations["en"]["secrets_setup_keys_confirm"] = "Setup SSH keys? (y/N)"
$script:Translations["en"]["secrets_step_tg_token"] = "[5/6] TELEGRAM_BOT_TOKEN"
$script:Translations["en"]["secrets_enter_tg_token"] = "Enter Telegram bot token (get from @BotFather)"
$script:Translations["en"]["secrets_tg_token_format"] = "Format: 1234567890:ABCdefGHIjklMNOpqrsTUVwxyz"
$script:Translations["en"]["secrets_token_label"] = "Token"
$script:Translations["en"]["secrets_step_tg_chat"] = "[6/6] TELEGRAM_ADMIN_CHAT_ID"
$script:Translations["en"]["secrets_chat_label"] = "Chat ID"
$script:Translations["en"]["secrets_summary_title"] = "Configuration complete!"
$script:Translations["en"]["secrets_summary_count"] = "Configured secrets: {0}/6"
$script:Translations["en"]["secrets_available_in_actions"] = "Secrets are now available in GitHub Actions workflows"
$script:Translations["en"]["secrets_repo_url"] = "Repository: https://github.com/{0}/settings/secrets/actions"
$script:Translations["en"]["secrets_list_title"] = "=== Configured Secrets ==="
$script:Translations["en"]["secrets_required_status"] = "Required secrets status:"
$script:Translations["en"]["secrets_not_configured"] = "(not configured)"
$script:Translations["en"]["secrets_full_list"] = "Full secrets list:"
$script:Translations["en"]["secrets_error_config_first"] = "Error: Configure GitHub token and repository first"
$script:Translations["en"]["secrets_complete_options"] = "Complete options 1 and 2 from the main menu"
$script:Translations["en"]["secrets_gh_auth_failed"] = "Failed to authenticate with GitHub CLI"
$script:Translations["en"]["secrets_check_token"] = "Check your token and try again"
$script:Translations["en"]["secrets_error_setting"] = "Error setting secret {0}"

$script:Translations["ru"]["secrets_testing_ssh"] = "Тестирование SSH подключения к {0}@{1}:{2}..."
$script:Translations["ru"]["secrets_ssh_port_ok"] = "SSH порт доступен"
$script:Translations["ru"]["secrets_ssh_port_fail"] = "Не удается подключиться к SSH серверу"
$script:Translations["ru"]["secrets_check_list"] = "Пожалуйста, проверьте:"
$script:Translations["ru"]["secrets_check_host"] = "IP/имя хоста правильное: {0}"
$script:Translations["ru"]["secrets_check_port"] = "Порт правильный: {0}"
$script:Translations["ru"]["secrets_check_server"] = "SSH сервер запущен"
$script:Translations["ru"]["secrets_check_firewall"] = "Брандмауэр разрешает подключения"
$script:Translations["ru"]["secrets_checking_keys"] = "Проверка существующих SSH ключей..."
$script:Translations["ru"]["secrets_ssh_success_keys"] = "SSH подключение успешно (используются существующие ключи)"
$script:Translations["ru"]["secrets_note_keys_exist"] = "Примечание: У вас уже настроены SSH ключи для этого сервера"
$script:Translations["ru"]["secrets_password_not_needed"] = "Аутентификация по паролю может не понадобиться"
$script:Translations["ru"]["secrets_auto_test_unreliable"] = "Автоматическое тестирование пароля ненадежно на Windows"
$script:Translations["ru"]["secrets_verify_manually"] = "Пожалуйста, проверьте вручную:"
$script:Translations["ru"]["secrets_run_command"] = "Выполните эту команду: ssh {0}@{1}"
$script:Translations["ru"]["secrets_can_connect"] = "Можете ли вы подключиться вручную с этой командой? (y/N)"
$script:Translations["ru"]["secrets_manual_verify_ok"] = "Ручная проверка успешна"
$script:Translations["ru"]["secrets_creds_saved"] = "Учетные данные будут сохранены в GitHub Secrets"
$script:Translations["ru"]["secrets_verify_creds"] = "Пожалуйста, проверьте ваши учетные данные"
$script:Translations["ru"]["secrets_check"] = "Проверьте:"
$script:Translations["ru"]["secrets_host"] = "Хост: {0}"
$script:Translations["ru"]["secrets_port"] = "Порт: {0}"
$script:Translations["ru"]["secrets_username"] = "Имя пользователя: {0}"
$script:Translations["ru"]["secrets_password_hidden"] = "Пароль: (скрыт)"
$script:Translations["ru"]["secrets_error_testing"] = "Ошибка тестирования подключения: {0}"
$script:Translations["ru"]["secrets_note_limited"] = "Примечание: Автоматическое тестирование SSH ограничено на Windows"
$script:Translations["ru"]["secrets_if_manual_ok"] = "Если вы можете подключиться вручную с 'ssh {0}@{1}', учетные данные правильные"
$script:Translations["ru"]["secrets_ssh_setup_title"] = "=== Настройка SSH ключей ==="
$script:Translations["ru"]["secrets_generating_key"] = "Генерация пары SSH ключей..."
$script:Translations["ru"]["secrets_key_generated"] = "Пара SSH ключей сгенерирована"
$script:Translations["ru"]["secrets_key_gen_failed"] = "Не удалось сгенерировать SSH ключ"
$script:Translations["ru"]["secrets_using_existing"] = "Используется существующий SSH ключ: {0}"
$script:Translations["ru"]["secrets_copying_key"] = "Копирование публичного ключа на сервер..."
$script:Translations["ru"]["secrets_key_copied"] = "Публичный ключ скопирован на сервер"
$script:Translations["ru"]["secrets_saving_private"] = "Сохранение приватного ключа в GitHub secret..."
$script:Translations["ru"]["secrets_private_key_ok"] = "SSH_PRIVATE_KEY настроен"
$script:Translations["ru"]["secrets_setup_complete"] = "Настройка SSH ключей завершена!"
$script:Translations["ru"]["secrets_passwordless"] = "Теперь вы можете использовать SSH аутентификацию без пароля"
$script:Translations["ru"]["secrets_note_remove_pass"] = "Примечание: Вы можете удалить secret SSH_PASSWORD, если используете только ключи"
$script:Translations["ru"]["secrets_key_copy_failed"] = "Не удалось скопировать публичный ключ на сервер"
$script:Translations["ru"]["secrets_manual_copy"] = "Вы можете скопировать ключ вручную:"
$script:Translations["ru"]["secrets_pubkey_location"] = "Расположение публичного ключа: {0}"
$script:Translations["ru"]["secrets_on_server_run"] = "На сервере выполните:"
$script:Translations["ru"]["secrets_pubkey_not_found"] = "Файл публичного ключа не найден"
$script:Translations["ru"]["secrets_chatid_title"] = "=== Как получить Telegram Chat ID ==="
$script:Translations["ru"]["secrets_chatid_step1"] = "1. Откройте @userinfobot в Telegram"
$script:Translations["ru"]["secrets_chatid_step2"] = "2. Отправьте команду /start"
$script:Translations["ru"]["secrets_chatid_step3"] = "3. Скопируйте ваш ID (число, например: 123456789)"
$script:Translations["ru"]["secrets_chatid_group"] = "Или для группы:"
$script:Translations["ru"]["secrets_chatid_group1"] = "1. Добавьте @userinfobot в группу"
$script:Translations["ru"]["secrets_chatid_group2"] = "2. ID группы начинается с минуса (например: -100123456789)"
$script:Translations["ru"]["secrets_gh_not_installed"] = "GitHub CLI (gh) не установлен"
$script:Translations["ru"]["secrets_gh_required"] = "GitHub CLI требуется для автоматической настройки secrets."
$script:Translations["ru"]["secrets_install_now"] = "Установить сейчас? (требуется winget)"
$script:Translations["ru"]["secrets_install_yes"] = "1. Да, установить через winget"
$script:Translations["ru"]["secrets_install_manual"] = "2. Нет, я установлю вручную"
$script:Translations["ru"]["secrets_install_cancel"] = "3. Отмена"
$script:Translations["ru"]["secrets_select_option"] = "Выберите опцию (1-3)"
$script:Translations["ru"]["secrets_installing_gh"] = "Установка GitHub CLI..."
$script:Translations["ru"]["secrets_gh_installed"] = "GitHub CLI установлен"
$script:Translations["ru"]["secrets_restart_script"] = "Перезапустите скрипт для применения изменений"
$script:Translations["ru"]["secrets_install_error"] = "Ошибка установки: {0}"
$script:Translations["ru"]["secrets_install_manual_msg"] = "Установите GitHub CLI вручную:"
$script:Translations["ru"]["secrets_or_via_winget"] = "Или через winget:"
$script:Translations["ru"]["secrets_authenticating"] = "Аутентификация с GitHub CLI..."
$script:Translations["ru"]["secrets_auth_success"] = "Аутентификация успешна"
$script:Translations["ru"]["secrets_auth_failed"] = "Аутентификация не удалась"
$script:Translations["ru"]["secrets_error"] = "Ошибка: {0}"
$script:Translations["ru"]["secrets_config_title"] = "=== Настройка GitHub Secrets ==="
$script:Translations["ru"]["secrets_repository"] = "Репозиторий: {0}"
$script:Translations["ru"]["secrets_will_configure"] = "Будут настроены следующие secrets:"
$script:Translations["ru"]["secrets_ssh_host_desc"] = "1. SSH_HOST - IP адрес сервера"
$script:Translations["ru"]["secrets_ssh_port_desc"] = "2. SSH_PORT - SSH порт (по умолчанию: 22)"
$script:Translations["ru"]["secrets_ssh_user_desc"] = "3. SSH_USER - имя пользователя SSH"
$script:Translations["ru"]["secrets_ssh_pass_desc"] = "4. SSH_PASSWORD - пароль SSH"
$script:Translations["ru"]["secrets_tg_token_desc"] = "5. TELEGRAM_BOT_TOKEN - токен Telegram бота"
$script:Translations["ru"]["secrets_tg_chat_desc"] = "6. TELEGRAM_ADMIN_CHAT_ID - ваш Telegram Chat ID"
$script:Translations["ru"]["secrets_continue"] = "Продолжить? (y/N)"
$script:Translations["ru"]["secrets_cancelled"] = "Отменено"
$script:Translations["ru"]["secrets_step_ssh_host"] = "[1/6] SSH_HOST"
$script:Translations["ru"]["secrets_enter_host"] = "Введите IP адрес или имя хоста сервера"
$script:Translations["ru"]["secrets_example_host"] = "Пример: 192.168.1.100 или server.example.com"
$script:Translations["ru"]["secrets_host_label"] = "Хост"
$script:Translations["ru"]["secrets_skipped"] = "Пропущено"
$script:Translations["ru"]["secrets_saving"] = "Сохранение {0}..."
$script:Translations["ru"]["secrets_configured"] = "{0} настроен"
$script:Translations["ru"]["secrets_step_ssh_port"] = "[2/6] SSH_PORT"
$script:Translations["ru"]["secrets_enter_port"] = "Введите SSH порт (нажмите Enter для порта по умолчанию 22)"
$script:Translations["ru"]["secrets_port_label"] = "Порт"
$script:Translations["ru"]["secrets_step_ssh_user"] = "[3/6] SSH_USER"
$script:Translations["ru"]["secrets_enter_user"] = "Введите имя пользователя SSH"
$script:Translations["ru"]["secrets_example_user"] = "Пример: root, ubuntu, admin"
$script:Translations["ru"]["secrets_user_label"] = "Имя пользователя"
$script:Translations["ru"]["secrets_step_ssh_pass"] = "[4/6] SSH_PASSWORD"
$script:Translations["ru"]["secrets_enter_pass"] = "Введите пароль SSH"
$script:Translations["ru"]["secrets_pass_label"] = "Пароль"
$script:Translations["ru"]["secrets_test_title"] = "=== Тест SSH подключения ==="
$script:Translations["ru"]["secrets_test_now"] = "Протестировать SSH подключение сейчас? (y/N)"
$script:Translations["ru"]["secrets_setup_keys_title"] = "=== Настройка SSH ключей ==="
$script:Translations["ru"]["secrets_setup_keys_question"] = "Хотите ли вы настроить SSH доступ без пароля используя SSH ключи?"
$script:Translations["ru"]["secrets_setup_keys_will"] = "Это выполнит:"
$script:Translations["ru"]["secrets_setup_keys_step1"] = "1. Генерацию пары SSH ключей (если не существует)"
$script:Translations["ru"]["secrets_setup_keys_step2"] = "2. Копирование публичного ключа на сервер"
$script:Translations["ru"]["secrets_setup_keys_step3"] = "3. Настройку secret SSH_PRIVATE_KEY для GitHub Actions"
$script:Translations["ru"]["secrets_setup_keys_confirm"] = "Настроить SSH ключи? (y/N)"
$script:Translations["ru"]["secrets_step_tg_token"] = "[5/6] TELEGRAM_BOT_TOKEN"
$script:Translations["ru"]["secrets_enter_tg_token"] = "Введите токен Telegram бота (получите от @BotFather)"
$script:Translations["ru"]["secrets_tg_token_format"] = "Формат: 1234567890:ABCdefGHIjklMNOpqrsTUVwxyz"
$script:Translations["ru"]["secrets_token_label"] = "Токен"
$script:Translations["ru"]["secrets_step_tg_chat"] = "[6/6] TELEGRAM_ADMIN_CHAT_ID"
$script:Translations["ru"]["secrets_chat_label"] = "Chat ID"
$script:Translations["ru"]["secrets_summary_title"] = "Настройка завершена!"
$script:Translations["ru"]["secrets_summary_count"] = "Настроено secrets: {0}/6"
$script:Translations["ru"]["secrets_available_in_actions"] = "Secrets теперь доступны в GitHub Actions workflows"
$script:Translations["ru"]["secrets_repo_url"] = "Репозиторий: https://github.com/{0}/settings/secrets/actions"
$script:Translations["ru"]["secrets_list_title"] = "=== Настроенные Secrets ==="
$script:Translations["ru"]["secrets_required_status"] = "Статус требуемых secrets:"
$script:Translations["ru"]["secrets_not_configured"] = "(не настроен)"
$script:Translations["ru"]["secrets_full_list"] = "Полный список secrets:"
$script:Translations["ru"]["secrets_error_config_first"] = "Ошибка: Сначала настройте токен GitHub и репозиторий"
$script:Translations["ru"]["secrets_complete_options"] = "Завершите опции 1 и 2 из главного меню"
$script:Translations["ru"]["secrets_gh_auth_failed"] = "Не удалось аутентифицироваться с GitHub CLI"
$script:Translations["ru"]["secrets_check_token"] = "Проверьте ваш токен и попробуйте снова"
$script:Translations["ru"]["secrets_error_setting"] = "Ошибка установки secret {0}"


# Loading status
$script:Translations["en"]["status_loading"] = "Loading status..."
$script:Translations["en"]["status_loading_docker"] = "Checking Docker containers"

$script:Translations["ru"]["status_loading"] = "Загрузка статуса..."
$script:Translations["ru"]["status_loading_docker"] = "Проверка Docker контейнеров"


# Docker error messages
$script:Translations["en"]["docker_error_empty_name"] = "Container name cannot be empty"
$script:Translations["ru"]["docker_error_empty_name"] = "Имя контейнера не может быть пустым"
